### ISSUE TITLE
Example prometheus config

### ISSUE THREAD

**Issue by oysstr** [DagensNyheter/logstash_exporter#1]
Hi.

Thanks a lot for creating this exporter, it works great.
Do you by any chance have a example prometheus dashboard lying around?

**Comment by christoe** [comment]
Hi,

Thanks for you interest in logstash_exporter! If you by Prometheus Dashboard mean a PromDash dashboard, then no, unfortunately. We're using Grafana to visualize our metrics. Also, my experience is that the dashboards is greatly dependent on the surrounding infrastructure and current issues at hand, which makes it hard to create a generic dashboard. Our Logstash dashboards are created from data from a lot of different sources, e.g. node_exporter, redis_exporter, statsd_exporter and logstash_exporter, and they would not make sense to you if you were not running an identical setup.

It's easy to setup dashboards if you know what you're looking for, start for example with generic ones, such as plugin durations, plugin failure rates and different jvm stats.
